---
version: '3.9'

services:
  plex-dvr-hls:
    image: ghcr.io/mhhplumber/plex-dvr-hls:latest
    container_name: plex-dvr-hls
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /home/plex-dvr-hls:/config
    ports:
      - 5004:5004
    restart: always
