---
version: '3.9'

services:
  plex-svr-hls:
    image: ghcr.io/mhhplumber/plex-dvr-hls:latest
    container_name: plex-dvr-hls
    volumes:
      - /home/plex-dvr-hls:/config
    ports:
      - 5004:5004
